#ifndef MAIN_H
#define MAIN_H
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <math.h>

#define SELECTION_QUIT (-1)
#define SELECTION_CALCULATOR 0
#define SELECTION_ELECTRIC 1
#define SELECTION_PARALLEL_PLATE 4
#define SELECTION_TRIGONOMETRY 5
#define SELECTION_NEWTONIAN 6
#define SELECTION_CIRCUITS 7
#define SELECTION_MAGNETIC 8
#define SELECTION_EM_INDUCTION 9
#define SELECTION_OPTICS 10
#define SELECTION_EM_WAVES 11
#define SELECTION_WAVE_INTERFERENCE 12
#define SELECTION_RELATIVITY 13
#define SELECTION_WAVE_PARTICLE_DUALITY 14
#define SELECTION_ATOMS 15
#define SELECTION_NUCLEAR 16

#define SELECTION_MAX 16
#endif